//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPS_Solution.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.Histories = new HashSet<History>();
            this.RecommendProducts = new HashSet<RecommendProduct>();
        }
    
        public string Username { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public int RoleID { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual ICollection<History> Histories { get; set; }
        public virtual ICollection<RecommendProduct> RecommendProducts { get; set; }
    }
}
