//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPS_Solution.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttributeDictionary
    {
        public int ID { get; set; }
        public string Codetype { get; set; }
        public string Name { get; set; }
        public double WeightCriteraPoint { get; set; }
    }
}
