//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPS_Solution.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Codetype
    {
        public Codetype()
        {
            this.ParseAttributes = new HashSet<ParseAttribute>();
        }
    
        public string ID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<ParseAttribute> ParseAttributes { get; set; }
    }
}
