//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPS_Solution.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public History()
        {
            this.HistoryDetails = new HashSet<HistoryDetail>();
        }
    
        public int ID { get; set; }
        public string Username { get; set; }
        public System.DateTime CompareTime { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual ICollection<HistoryDetail> HistoryDetails { get; set; }
    }
}
