//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPS_Solution.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogFile
    {
        public int ID { get; set; }
        public string Filename { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public bool IsActive { get; set; }
    }
}
