//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPS_Solution.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductAttribute
    {
        public int ID { get; set; }
        public int CPU { get; set; }
        public int HDD { get; set; }
        public int VGA { get; set; }
        public int RAM { get; set; }
        public int Display { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
