//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPS_Solution.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.ProductAlias = new HashSet<ProductAlia>();
            this.RatingProducts = new HashSet<RatingProduct>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string URL { get; set; }
        public Nullable<double> Price { get; set; }
        public double TotalPoint { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<ProductAlia> ProductAlias { get; set; }
        public virtual ProductAttribute ProductAttribute { get; set; }
        public virtual ICollection<RatingProduct> RatingProducts { get; set; }
    }
}
