//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPS_Solution.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class AliasProduct
    {
        public int ID { get; set; }
        public int ProductID { get; set; }
        public string Name { get; set; }
        public string URL { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> StoreID { get; set; }
        public Nullable<int> BrandID { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<bool> IsMain { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual Product Product { get; set; }
        public virtual Store Store { get; set; }
    }
}
