//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPS_Solution.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Brand
    {
        public Brand()
        {
            this.AliasProducts = new HashSet<AliasProduct>();
        }
    
        public int ID { get; set; }
        public string BrandName { get; set; }
    
        public virtual ICollection<AliasProduct> AliasProducts { get; set; }
    }
}
