//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPS_Solution.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParseAttribute
    {
        public int ID { get; set; }
        public string Codetype { get; set; }
        public string ParseAttributelink { get; set; }
        public string NameXPath { get; set; }
        public string PagingXPath { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Codetype Codetype1 { get; set; }
    }
}
