//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPS_Solution.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecommendProduct
    {
        public int ID { get; set; }
        public string Username { get; set; }
        public bool IsReceive { get; set; }
        public bool IsMailSent { get; set; }
        public string Parselink { get; set; }
        public string Email { get; set; }
        public Nullable<bool> IsApprove { get; set; }
        public Nullable<bool> IsTrue { get; set; }
        public Nullable<System.DateTime> RecommendTime { get; set; }
        public bool IsSeen { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
