//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPS_Solution.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecommendProduct
    {
        public int ID { get; set; }
        public string Username { get; set; }
        public string Parselink { get; set; }
        public string Name { get; set; }
        public string RAM { get; set; }
        public string HDD { get; set; }
        public string VGA { get; set; }
        public string Display { get; set; }
        public string CPU { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> RecommendTime { get; set; }
    }
}
