//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportExcel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class alias
    {
        public int ID { get; set; }
        public int productID { get; set; }
        public string Name { get; set; }
    
        public virtual product product { get; set; }
    }
}
